### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mxtilx** [infstellar/genshin_impact_assistant#102]
source.task.task_manager:start_stop_task:104 - 任务MissionTask启动。
2023-08-17 18:12:26.075 | INFO     | source.mission.mission_manager:loop:33 - Mission MissionCrystalfly Start.
2023-08-17 18:12:26.349 | INFO     | source.api.pdocr_api:<module>:4 - 正在创建OCR对象
2023-08-17 18:12:27.055 | CRITICAL | source.api.pdocr_api:<module>:14 - 导入paddleocr时错误; err code: 001
2023-08-17 18:12:27.344 | ERROR    | source.api.pdocr_api:<module>:15 - FastDeploy initalized failed! Error: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Traceback (most recent call last):

  File "E:\anconda3\envs\gs\lib\site-packages\fastdeploy\c_lib_wrap.py", line 164, in <module>
    from .libs.fastdeploy_main import *

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\anconda3\envs\gs\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000022CD34AE0D8>
    └ <MissionManager(Thread-11, started daemon 1636)>

  File "E:\anconda3\envs\gs\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function BaseThreading.run at 0x0000022CD9869798>
    └ <MissionManager(Thread-11, started daemon 1636)>

  File "E:\genshin_impact_assistant\source\common\base_threading.py", line 170, in run
    self.loop()
    │    └ <function MissionManager.loop at 0x0000022CEB7FF948>
    └ <MissionManager(Thread-11, started daemon 1636)>

  File "E:\genshin_impact_assistant\source\mission\mission_manager.py", line 34, in loop
    self.exec_mission(mission_name)
    │    │            └ 'MissionCrystalfly'
    │    └ <function MissionManager.exec_mission at 0x0000022CEB7FF798>
    └ <MissionManager(Thread-11, started daemon 1636)>

  File "E:\genshin_impact_assistant\source\mission\mission_manager.py", line 19, in exec_mission
    mission = missions.mission_index.get_mission_object(mission_name)
              │        │             │                  └ 'MissionCrystalfly'
              │        │             └ <function get_mission_object at 0x0000022CEB7FF3A8>
              │        └ <module 'missions.mission_index' from 'E:\\genshin_impact_assistant\\missions\\mission_index.py'>
              └ <module 'missions' (namespace)>

  File "E:\genshin_impact_assistant\missions\mission_index.py", line 22, in get_mission_object
    import missions.MissionCrystalfly

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "E:\genshin_impact_assistant\missions\MissionCrystalfly.py", line 1, in <module>
    from source.mission.mission_template import MissionExecutor

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "E:\genshin_impact_assistant\source\mission\mission_template.py", line 1, in <module>
    from source.teyvat_move import teyvat_move_flow_upgrade

  File "<frozen importlib._bootstrap>", line 1035, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "E:\genshin_impact_assistant\source\teyvat_move\teyvat_move_flow_upgrade.py", line 5, in <module>
    from source.pickup.pickup_operator import PickupOperator

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "E:\genshin_impact_assistant\source\pickup\pickup_operator.py", line 6, in <module>
    from source.api.pdocr_complete import ocr

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "E:\genshin_impact_assistant\source\api\pdocr_complete.py", line 1, in <module>
    from source.api.pdocr_api import PaddleOcrFastDeploy

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

> File "E:\genshin_impact_assistant\source\api\pdocr_api.py", line 12, in <module>
    import fastdeploy

  File "E:\anconda3\envs\gs\lib\site-packages\fastdeploy\__init__.py", line 122, in <module>
    from .c_lib_wrap import (

  File "E:\anconda3\envs\gs\lib\site-packages\fastdeploy\c_lib_wrap.py", line 166, in <module>
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")

RuntimeError: FastDeploy initalized failed! Error: DLL load failed: A dynamic link library (DLL) initialization routine failed.

**Comment by infstellar** [comment]
缺DLL

**Comment by infstellar** [comment]
看起来你是从源码运行的
没遇到过这个问题,你搜一下看看把

可能的方案
- 检查CPU是否支持AVX指令集
- 安装C++全家桶
- 从PGPL运行
