### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by 013A** [infstellar/genshin_impact_assistant#114]
一开始以为是网路或加速器问题，但加速器都关闭后却问题依旧
以下是日誌
2023-10-07 12:36:09.475 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------------------------------+
2023-10-07 12:36:09.475 | INFO     | pgpl.logger:hr:74 - |                    WELCOME TO PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-10-07 12:36:09.476 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------------------------------+
2023-10-07 12:36:09.476 | INFO     | pgpl.logger:hr:69 - <<< 该程序在GITHUB免费开源 >>>
2023-10-07 12:36:09.480 | INFO     | pgpl.logger:hr:69 - <<< 请在HTTPS://GITHUB.COM/INFSTELLAR/PYTHON-GIT-PROGRAM-LAUNCHER查看使用说明 >>>
2023-10-07 12:36:09.504 | INFO     | pgpl.utils:execute:269 - "D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
2023-10-07 12:36:09.582 | INFO     | pgpl.utils:execute:287 - [ failure ], error_code: 2 stdout:  stderr: D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py': [Errno 2] No such file or directory

2023-10-07 12:36:09.583 | INFO     | pgpl.utils:show_error:231 - Update failed
2023-10-07 12:36:09.583 | INFO     | pgpl.utils:show_error:233 - 
2023-10-07 12:36:09.584 | INFO     | pgpl.utils:show_error:234 - Last command: "D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/Lib/site-packages/pip/__main__.py" --version
error_code: 2
2023-10-07 12:36:09.584 | INFO     | pgpl.utils:error_checking:226 - Running automatic error checking...
2023-10-07 12:36:09.584 | WARNING  | pgpl.managers:run:352 - pip失败，重装python
2023-10-07 12:36:09.605 | INFO     | pgpl.utils:verify_path:136 - dir D:\genshin auto\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib has been created
2023-10-07 12:36:09.611 | INFO     | pgpl.utils:info:247 - url: https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip
2023-10-07 12:36:09.866 | INFO     | pgpl.utils:download_url:75 - 下载url:https://mirrors.huaweicloud.com/python/3.7.6/python-3.7.6-embed-amd64.zip -> D:\genshin auto\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python-3.7.6-amd64.zip
2023-10-07 12:36:13.456 | INFO     | pgpl.logger:hr:73 - +--------------------------------------------------------+
2023-10-07 12:36:13.457 | INFO     | pgpl.logger:hr:74 - |                    下载PYTHON成功，解压压缩包                    |
2023-10-07 12:36:13.462 | INFO     | pgpl.logger:hr:75 - +--------------------------------------------------------+
2023-10-07 12:36:13.655 | INFO     | pgpl.logger:hr:73 - +------------------------------------------------------+
2023-10-07 12:36:13.655 | INFO     | pgpl.logger:hr:74 - |                    INSTALLING PIP                    |
2023-10-07 12:36:13.656 | INFO     | pgpl.logger:hr:75 - +------------------------------------------------------+
2023-10-07 12:36:13.656 | INFO     | pgpl.utils:execute:269 - python "D:/genshin auto/PGPL-2.2.0/toolkit/Lib/site-packages/pip/__main__.py" config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
2023-10-07 12:36:15.018 | TRACE    | pgpl.utils:run_command:195 - ['D:\\genshin auto\\PGPL-2.2.0', 'D:\\genshin auto\\PGPL-2.2.0\\toolkit', 'D:\\genshin auto\\PGPL-2.2.0\\toolkit\\Lib', 'D:\\genshin auto\\PGPL-2.2.0\\toolkit\\DLLs', 'D:\\genshin auto\\PGPL-2.2.0\\toolkit\\Scripts']
2023-10-07 12:36:15.019 | TRACE    | pgpl.utils:run_command:195 - Writing to C:\Users\cadye\AppData\Roaming\pip\pip.ini
2023-10-07 12:36:15.120 | INFO     | pgpl.utils:execute:296 - [ success ]
2023-10-07 12:36:15.121 | INFO     | pgpl.utils:execute:269 - "D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/genshin auto/PGPL-2.2.0/toolkit/get-pip.py" --no-setuptools --no-wheel
2023-10-07 12:36:19.965 | TRACE    | pgpl.utils:run_command:195 - Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
2023-10-07 12:36:31.691 | INFO     | pgpl.utils:execute:287 - [ failure ], error_code: 1 stdout:  stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024F9BB38F48>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/

WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024F9B68B748>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/

WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024F9B68BC48>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/

WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024F9B6962C8>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024F9B696908>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/pip/

ERROR: Could not find a version that satisfies the requirement pip (from versions: none)

ERROR: No matching distribution found for pip

2023-10-07 12:36:31.692 | INFO     | pgpl.utils:show_error:231 - Update failed
2023-10-07 12:36:31.692 | INFO     | pgpl.utils:show_error:233 - 
2023-10-07 12:36:31.692 | INFO     | pgpl.utils:show_error:234 - Last command: "D:/genshin auto/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" "D:/genshin auto/PGPL-2.2.0/toolkit/get-pip.py" --no-setuptools --no-wheel
error_code: 1
2023-10-07 12:36:31.692 | INFO     | pgpl.utils:error_checking:226 - Running automatic error checking...
2023-10-07 12:36:31.693 | ERROR    | pgpl.pages:_start:196 - 
Traceback (most recent call last):

  File "D:\genshin auto\PGPL-2.2.0\pgpl\managers.py", line 350, in run
    self.execute(f'"{self.python_path}" "{self.python_folder}/Lib/site-packages/pip/__main__.py" --version')
    │    └ <function Command.execute at 0x000001FB1A2609D8>
    └ <pgpl.managers.PythonManager object at 0x000001FB1B3C5F08>

  File "D:\genshin auto\PGPL-2.2.0\pgpl\utils.py", line 293, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\genshin auto\PGPL-2.2.0\toolkit\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001FB17B20708>
    └ <Thread(Thread-4, started daemon 23076)>
  File "D:\genshin auto\PGPL-2.2.0\toolkit\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001FB17B204C8>
    └ <Thread(Thread-4, started daemon 23076)>
  File "D:\genshin auto\PGPL-2.2.0\toolkit\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x000001FB1A35DE58>}
    │    │        │    │        └ <Thread(Thread-4, started daemon 23076)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 23076)>
    │    └ <function put_buttons.<locals>.click_callback at 0x000001FB1A34FF78>
    └ <Thread(Thread-4, started daemon 23076)>
  File "D:\genshin auto\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-1u2hggC0ae', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x000001FB1A35DE58>
  File "D:\genshin auto\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x000001FB1B3B3D48>>]

> File "D:\genshin auto\PGPL-2.2.0\pgpl\pages.py", line 142, in _start
    PROGRAM_PYTHON_PATH = PythonManager(launching_config, self.pt).run()
                          │             │                 │    └ <pgpl.utils.ProgressTracker object at 0x000001FB1B3B3D88>
                          │             │                 └ <pgpl.pages.MainPage object at 0x000001FB1B3B3D48>
                          │             └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
                          └ <class 'pgpl.managers.PythonManager'>

  File "D:\genshin auto\PGPL-2.2.0\pgpl\managers.py", line 355, in run
    self.download_python_zip()
    │    └ <function PythonManager.download_python_zip at 0x000001FB1A34F318>
    └ <pgpl.managers.PythonManager object at 0x000001FB1B3C5F08>

  File "D:\genshin auto\PGPL-2.2.0\pgpl\managers.py", line 268, in download_python_zip
    self.execute(f'"{self.python_path}" "{os.path.join(ROOT_PATH, "toolkit", "get-pip.py")}" --no-setuptools --no-wheel')
    │    └ <function Command.execute at 0x000001FB1A2609D8>
    └ <pgpl.managers.PythonManager object at 0x000001FB1B3C5F08>

  File "D:\genshin auto\PGPL-2.2.0\pgpl\utils.py", line 293, in execute
    raise ExecutionError
          └ <class 'pgpl.utils.ExecutionError'>

pgpl.utils.ExecutionError
![image](https://github.com/infstellar/genshin_impact_assistant/assets/132829623/9c825911-bf68-4737-b02d-c47c711c7d47)

**Comment by infstellar** [comment]
看起来还是网络问题,https连接失败
