### ISSUE TITLE
我要爆炸了，重装系统都尝试了，故障依旧。。。

### ISSUE THREAD

**Issue by mcxiaochenn** [infstellar/genshin_impact_assistant#123]
Traceback (most recent call last):
  File "genshin_assistant.py", line 6, in <module>
    import source.util
  File "D:\!!!\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\source\util.py", line 3, in <module>
    import win32gui, win32process, psutil, ctypes, pickle, traceback
ModuleNotFoundError: No module named 'win32gui'
请按任意键继续. . .

**Comment by mcxiaochenn** [comment]
PS D:\xiazai\genshin_impact_assistant-1.0.0> & C:/Users/mcxia/AppData/Local/Programs/Python/Python37/python.exe d:/xiazai/genshin_impact_assistant-1.0.0/genshin_assistant.py
zh_CN
python "d:\xiazai\genshin_impact_assistant-1.0.0/source/msgfmt.py" -o "d:\xiazai\genshin_impact_assistant-1.0.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "d:\xiazai\genshin_impact_assistant-1.0.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
2023-11-05 11:21:25.536 | ERROR    | source.util:<module>:90 - 请用管理员权限运行
sha-1 verify cost: 0.32498812675476074
2023-11-05 11:21:26.069 | WARNING  | source.common.static_lib:get_handle:27 - 找不到句柄
2023-11-05 11:21:26.074 | INFO     | source.interaction.interaction_core:__init__:73 - InteractionBGD created
[ WARN:0@0.890] global loadsave.cpp:248 cv::findDecoder imread_('assets\imgs\Windows\UI\common\ButtonUISwitchToTimeMenu.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "d:/xiazai/genshin_impact_assistant-1.0.0/genshin_assistant.py", line 20, in <module>
    from source.webio import webio
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\webio\webio.py", line 15, in <module>
    from source.webio.webpages.video2path import VideoToPathPage
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\webio\webpages\video2path.py", line 6, in <module>
    from source.ui.ui import ui_control
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\ui\ui.py", line 2, in <module>
    from source.manager.asset import *
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\manager\asset.py", line 8, in <module>
    ButtonUISwitchToTimeMenu = Button(black_offset = 15, print_log=LOG_WHEN_TRUE)
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\manager\button_manager.py", line 19, in __init__
    threshold=threshold, win_page=win_page, win_text=win_text, print_log=print_log, cap_posi=cap_posi, offset = offset)
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\manager\img_manager.py", line 72, in __init__
    self.bbg_posi = get_bbox(self.raw_image)
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\util.py", line 436, in get_bbox
    if image_channel(image) == 3:
  File "d:\xiazai\genshin_impact_assistant-1.0.0\source\util.py", line 459, in image_channel
    return image.shape[2] if len(image.shape) == 3 else 0
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by mcxiaochenn** [comment]
现在的问题是这样，就很难受，源代码运行总感觉缺了什么东西，还特地把我python环境的版本切换到了3.7.6就是不行，一开始还提示少了imgs_index.json我从一键启动的文件夹里找到了，这玩意我是真不会改了，大佬能不能帮忙看看，作者都不看github的嘛

**Comment by infstellar** [comment]
可能由于pyqt5无法编译引起,已修复
