### ISSUE TITLE
BUG无法启动

### ISSUE THREAD

**Issue by SENyiAi** [infstellar/genshin_impact_assistant#127]
zh_CN
python "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib/source/msgfmt.py" -o "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
sha-1 verify cost: 0.307462215423584
2023-11-13 00:50:05.706 | INFO     | source.interaction.interaction_core:__init__:73 - InteractionBGD created
D:\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\lib\site-packages\pydantic\_internal\_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'keep_untouched' has been renamed to 'ignored_types'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "genshin_assistant.py", line 20, in <module>
    from source.webio import webio
  File "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\source\webio\webio.py", line 15, in <module>
    from source.webio.webpages.video2path import VideoToPathPage
  File "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\source\webio\webpages\video2path.py", line 10, in <module>
    from source.map.map import genshin_map
  File "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\source\map\map.py", line 8, in <module>
    from source.map.data.teleporter_zh_CN import DICT_TELEPORTER
  File "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\source\map\data\teleporter_zh_CN.py", line 1, in <module>
    from source.map.extractor.reader import TeleporterModel
  File "D:\PGPL-2.2.0\repositories\GIA_Launcher_Download_Lib\source\map\extractor\reader.py", line 19, in <module>
    class PointInfoModel(BaseModel):
  File "D:\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\lib\site-packages\pydantic\_internal\_model_construction.py", line 105, in __new__
    namespace, config_wrapper.ignored_types, class_vars, base_field_names
  File "D:\PGPL-2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\lib\site-packages\pydantic\_internal\_model_construction.py", line 374, in inspect_namespace
    code='model-field-missing-annotation',
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `first_item = <cached_property.cached_property object at 0x000002741166D5C8>`. All model fields require a type annotation; if `first_item` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.4/u/model-field-missing-annotation

**Comment by infstellar** [comment]
你的pydanic版本太新了
