### ISSUE TITLE
源码运行后ModuleNotFoundError: No module named 'cached_property'怎么解决

### ISSUE THREAD

**Issue by qwe3123s** [infstellar/genshin_impact_assistant#168]
D:\tools\genshin_pgpl\genshin_impact_assistant>python genshin_assistant.py
zh_CN
python "D:\tools\genshin_pgpl\genshin_impact_assistant/source/msgfmt.py" -o "D:\tools\genshin_pgpl\genshin_impact_assistant\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "D:\tools\genshin_pgpl\genshin_impact_assistant\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
sha-1 verify cost: 0.3352377414703369
2024-07-24 20:35:23.798 | INFO     | source.interaction.interaction_core:__init__:78 - InteractionBGD created
Traceback (most recent call last):
  File "D:\tools\genshin_pgpl\genshin_impact_assistant\genshin_assistant.py", line 20, in <module>
    from source.webio import webio
  File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\webio\webio.py", line 12, in <module>
    from source.webio.webpages.collector_settings import CollectorSettingPage
  File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\webio\webpages\collector_settings.py", line 6, in <module>
    from source.funclib import collector_lib
  File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\funclib\collector_lib.py", line 160, in <module>
    from source.map.extractor.reader import PoiJsonApi, PointInfoModel
  File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\map\extractor\reader.py", line 4, in <module>
    from cached_property import cached_property
ModuleNotFoundError: No module named 'cached_property'

D:\tools\genshin_pgpl\genshin_impact_assistant>

**Comment by qwe3123s** [comment]
我用快速启动是
Traceback (most recent call last):
  File "genshin_assistant.py", line 6, in <module>
    import source.util
  File "D:\tools\genshin_pgpl\PGPL-2.4.0\repositories\GIA_Launcher_Download_Lib\source\util.py", line 3, in <module>
    import win32gui, win32process, psutil, ctypes, pickle, traceback
ModuleNotFoundError: No module named 'win32gui'
请按任意键继续. . .

**Comment by infstellar** [comment]
快速启动的PGPL版本是多少？发一下日志康康
源码安装的话，python版本是多少？

**Comment by qwe3123s** [comment]
> 快速启动的PGPL版本是多少？发一下日志康康 源码安装的话，python版本是多少？
[2024-07-24.log](https://github.com/user-attachments/files/16362506/2024-07-24.log)

PGPL版本是2.4.0   
py我最开始没有安装3.7.6，电脑里面有3.10的版本。后面我又安装的3.7.6，前后都是上面那个情况

**Comment by infstellar** [comment]
是不是开代理了

**Comment by infstellar** [comment]
然后python版本要3.7.6，不然requirements会装不上，还要记得克隆子模块

**Comment by Pevernow** [comment]
同一个问题。。。

**Comment by Pevernow** [comment]
> D:\tools\genshin_pgpl\genshin_impact_assistant>python genshin_assistant.py zh_CN python "D:\tools\genshin_pgpl\genshin_impact_assistant/source/msgfmt.py" -o "D:\tools\genshin_pgpl\genshin_impact_assistant\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "D:\tools\genshin_pgpl\genshin_impact_assistant\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po" sha-1 verify cost: 0.3352377414703369 2024-07-24 20:35:23.798 | INFO | source.interaction.interaction_core:**init**:78 - InteractionBGD created Traceback (most recent call last): File "D:\tools\genshin_pgpl\genshin_impact_assistant\genshin_assistant.py", line 20, in from source.webio import webio File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\webio\webio.py", line 12, in from source.webio.webpages.collector_settings import CollectorSettingPage File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\webio\webpages\collector_settings.py", line 6, in from source.funclib import collector_lib File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\funclib\collector_lib.py", line 160, in from source.map.extractor.reader import PoiJsonApi, PointInfoModel File "D:\tools\genshin_pgpl\genshin_impact_assistant\source\map\extractor\reader.py", line 4, in from cached_property import cached_property ModuleNotFoundError: No module named 'cached_property'
> 
> D:\tools\genshin_pgpl\genshin_impact_assistant>

缺两个依赖给我自己试出来了
pip install numpy==1.22.4
pip install cached-property

**Comment by infstellar** [comment]
你的Python版本是多少 @Pevernow

**Comment by Pevernow** [comment]
> 你的Python版本是多少 @Pevernow

3.10.11
