### ISSUE TITLE
[BUG] “验证通过”但“发生内部错误”

### ISSUE THREAD

**Issue by Pevernow** [infstellar/genshin_impact_assistant#178]
Traceback (most recent call last):
  File "C:\Users\34503\AppData\Local\Programs\Python\Python310\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
  File "C:\Users\34503\AppData\Local\Programs\Python\Python310\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
  File "C:\code\genshin_impact_assistant\source\webio\webpages\tavern2mission.py", line 158, in _generate_mission
    pos = correction_collection_position(pos, name=pin.pin[self.INPUT_COLLECTION_NAME])
  File "C:\code\genshin_impact_assistant\source\integration_json\funclib.py", line 21, in correction_collection_position
    possible_list = JIApi.data[name]
KeyError: '湖光铃兰'

![image](https://github.com/user-attachments/assets/18d941e9-e339-46e4-9f2d-7f536c03f6ce)

**Comment by Pevernow** [comment]
换成铁矿就没事了？？？
所以是不支持湖光铃兰？

**Comment by Pevernow** [comment]
不是哥们？
![image](https://github.com/user-attachments/assets/b611c440-ae28-4a3f-8956-6d4a55911eab)
![image](https://github.com/user-attachments/assets/32803364-842f-4cf1-9222-344642a64950)

**Comment by infstellar** [comment]
修了修了⁄(⁄⁄•⁄ω⁄•⁄⁄)⁄
