### ISSUE TITLE
[BUG] main分支最新，启动就报错

### ISSUE THREAD

**Issue by Pevernow** [infstellar/genshin_impact_assistant#184]
Running on all addresses.
Use http://198.18.0.1:22268/ to access the application
[ WARN:0@5.729] global loadsave.cpp:244 cv::findDecoder imread_('C:/Users/34503/AppData/Local/Programs/Python/Python310/lib/site-packages/gimapdev/GIMAP.png'): can't open/read file: check file path/integrity
Unhandled error in pywebio app
Traceback (most recent call last):
  File "C:\Users\34503\AppData\Local\Programs\Python\Python310\lib\site-packages\pywebio\session\threadbased.py", line 86, in main_task
    target()
  File "C:\code\genshin_impact_assistant\source\webio\webio.py", line 48, in main
    webio.manager.reg_page("Edit Path & Make Mission", TLPath2Mission())
  File "C:\code\genshin_impact_assistant\source\webio\webpages\TLPath2mission.py", line 57, in __init__
    self.gimap = MiniMapResource().RAWGIMAP
  File "C:\Users\34503\AppData\Local\Programs\Python\Python310\lib\site-packages\cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\code\genshin_impact_assistant\source\map\detection\resource.py", line 44, in RAWGIMAP
    image = cv2.cvtColor(cv2.imread(file), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by infstellar** [comment]
用python3.7.6

**Comment by Pevernow** [comment]
gimapdev==4.6.3解决

**Comment by Pevernow** [comment]
> 用python3.7.6

跟python版本没啥关系。

**Comment by infstellar** [comment]
emmmm
