### ISSUE TITLE
ImportError: DLL load failed while importing giayap: 找不到指定的模块。

### ISSUE THREAD

**Issue by Pevernow** [infstellar/genshin_impact_assistant#188]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\34503\AppData\Local\Programs\Python\Python310\lib\site-packages\giayap\__init__.py", line 46, in <module>
    from .giayap import *
ImportError: DLL load failed while importing giayap: 找不到指定的模块。

已安装giayap==0.0.5

**Comment by infstellar** [comment]
用python3.7.6试试，这个包编译的时候用的是3.7.6

**Comment by Pevernow** [comment]
> 用python3.7.6试试，这个包编译的时候用的是3.7.6

3.7.6已经已经是四年前的版本了。。。。。都过了维护期了

是时候迁移到3.10了吧，我试了一下基本上可以直接迁移的，除了这次的giayap其它都能直接用。

torch也该上2.x以上版本了，我用2.1.2也是可以直接兼容这个项目的。
1.13也有点过时了。。。

**Comment by Pevernow** [comment]
给每个项目单独装好几个G的环境，我硬盘有点不够用。。。。。

**Comment by Pevernow** [comment]
3.10兼容解决方案： pip install https://files.pythonhosted.org/packages/04/b8/3b91d5e53a36412f72f66c95dded40a9dd203780073e90ea7178f2dcc695/giayap-0.0.6.tar.gz
手动编译解决。

**Comment by Pevernow** [comment]
这个pydd写死了，我拿源码包自编译都没用.......................................
救不了

**Comment by infstellar** [comment]
去年迁移的时候爆炸了，所以没搞
能不能发一下3.10的适配的包版本，我看看能不能升级

**Comment by Pevernow** [comment]
> 去年迁移的时候爆炸了，所以没搞 能不能发一下3.10的适配的包版本，我看看能不能升级

就现在这个requirement.txt
![image](https://github.com/user-attachments/assets/4cfe6a55-b2c6-4443-a78c-a7ee59cc1d93)
numpy==1.22.4
并手动安装cached-property

**Comment by infstellar** [comment]
彳亍，有空看看

**Comment by Pevernow** [comment]
> 彳亍，有空看看

更新了吗，一周了（

**Comment by Pevernow** [comment]
> 彳亍，有空看看

@infstellar  有进展吗？（

**Comment by infstellar** [comment]
抱歉，上个星期没空 :(
这个升级要所有的PGPL一起升级，我得先改写PGPL的代码
