### ISSUE TITLE
【BUG】在委托战斗开始前始终报错中止

### ISSUE THREAD

**Issue by PengZhangSDF** [infstellar/genshin_impact_assistant#194]
在每个委托到达位置前的寻找仇恨阶段，就会报错停止这个委托。下面节选某一个委托前的中止片段。

![bug01](https://github.com/user-attachments/assets/61b4a11f-4a9a-4984-854b-11f6853a4da8)
2024-08-16 13:41:52.545 | DEBUG    | source.interaction.interaction_core:delay:604 - delay: 0.6985385987524092 |function name: move |comment: 
2024-08-16 13:41:53.251 | TRACE    | source.interaction.interaction_core:wrapper:41 -  operation: key_up | args: ('w',) | {} | function name: move & move_to_posi_LoopMode
2024-08-16 13:41:53.448 | ERROR    | source.mission.mission_template:loop:416 - ERROR in execute mission: source.mission.mission_template <lambda>() missing 1 required positional argument: 'x'
2024-08-16 13:41:53.448 | ERROR    | source.mission.mission_template:loop:417 - <lambda>() missing 1 required positional argument: 'x'
Traceback (most recent call last):

  File "F:\Users\live\Desktop\PGPL-2.3\installed_python\3.7.6_GIA_Launcher_Download_Lib\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000013C699AAAF8>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 17876)>

  File "F:\Users\live\Desktop\PGPL-2.3\installed_python\3.7.6_GIA_Launcher_Download_Lib\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function BaseThreading.run at 0x0000013C7A6079D8>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 17876)>

  File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\common\base_threading.py", line 218, in run
    self.loop()
    │    └ <function MissionExecutor.loop at 0x0000013C41B64A68>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 17876)>

> File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\mission\mission_template.py", line 408, in loop
    self.exec_mission()
    │    └ <function FightOnlyGeneral.exec_mission at 0x0000013C41A97A68>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 17876)>

  File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\commission\general\OnlyFight.py", line 13, in exec_mission
    self.circle_search(self.commission_position, stop_rule=STOP_RULE_COMBAT)
    │    │             │    │                              └ 'COMBAT'
    │    │             │    └ [3917.1225600000007, -5742.17216]
    │    │             └ <FightOnlyGeneral(source.mission.mission_template, started daemon 17876)>
    │    └ <function MissionExecutor.circle_search at 0x0000013C41B5FE58>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 17876)>

  File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\mission\mission_template.py", line 305, in circle_search
    if stop_func():
       └ <function MissionExecutor.<lambda> at 0x0000013C41B5FDC8>

TypeError: <lambda>() missing 1 required positional argument: 'x'
2024-08-16 13:41:53.459 | TRACE    | source.interaction.interaction_core:wrapper:41 -  operation: key_up | args: ('w',) | {} | function name: loop & run
2024-08-16 13:41:53.468 | DEBUG    | source.common.base_threading:pause_threading:47 - source.mission.mission_template pause threading
2024-08-16 13:41:53.468 | DEBUG    | source.common.base_threading:pause_threading:49 - source.mission.mission_template pause PickupOperator
2024-08-16 13:41:53.469 | DEBUG    | source.common.base_threading:pause_threading:49 - source.mission.mission_template pause TeyvatMoveFlow
2024-08-16 13:41:54.635 | DEBUG    | source.common.base_threading:_clean_sub_threading:181 - CommissionExecutor stop source.mission.mission_template
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:stop_threading:75 - source.mission.mission_template stopping.
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:_clean_sub_threading:181 - source.mission.mission_template stop PickupOperator
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:stop_threading:75 - PickupOperator stopping.
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:_clean_sub_threading:181 - source.mission.mission_template stop TeyvatMoveFlow
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:stop_threading:75 - TeyvatMoveFlow stopping.
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:_clean_sub_threading:181 - TeyvatMoveFlow stop SwitchCharacterOperator
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:stop_threading:75 - SwitchCharacterOperator stopping.
2024-08-16 13:41:54.637 | DEBUG    | source.common.base_threading:_clean_sub_threading:181 - SwitchCharacterOperator stop TacticOperator
2024-08-16 13:41:54.638 | DEBUG    | source.common.base_threading:stop_threading:75 - TacticOperator stopping.
2024-08-16 13:41:54.638 | DEBUG    | source.common.base_threading:_clean_sub_threading:181 - SwitchCharacterOperator stop AimOperator
2024-08-16 13:41:54.638 | DEBUG    | source.common.base_threading:stop_threading:75 - AimOperator stopping.
2024-08-16 13:41:54.638 | DEBUG    | source.common.base_threading:_clean_sub_threading:181 - TeyvatMoveFlow stop Thread-27
2024-08-16 13:41:54.638 | DEBUG    | source.common.base_threading:stop_threading:75 - Thread-27 stopping.
2024-08-16 13:41:54.640 | INFO     | source.commission.commission_executor:loop:39 - 委托失败。委托任务结束。
[2024-08-16.log](https://github.com/user-attachments/files/16633749/2024-08-16.log)

**Comment by PengZhangSDF** [comment]
问题解决了但是没有完全解决，我今天的每日委托打临危受命的时候遇到了相似的问题，只是这一次整个任务都结束了
[2024-08-23.log](https://github.com/user-attachments/files/16728131/2024-08-23.log)
![Uploading bug02.png…]()

**Comment by PengZhangSDF** [comment]
2024-08-23 19:45:25.846 | ERROR    | source.mission.mission_template:loop:416 - ERROR in execute mission: source.mission.mission_template <lambda>() missing 1 required positional argument: 'x'
2024-08-23 19:45:25.851 | ERROR    | source.mission.mission_template:loop:417 - <lambda>() missing 1 required positional argument: 'x'
Traceback (most recent call last):

  File "F:\Users\live\Desktop\PGPL-2.3\installed_python\3.7.6_GIA_Launcher_Download_Lib\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000291D4CA8A68>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 16508)>

  File "F:\Users\live\Desktop\PGPL-2.3\installed_python\3.7.6_GIA_Launcher_Download_Lib\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function BaseThreading.run at 0x00000291E74F89D8>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 16508)>

  File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\common\base_threading.py", line 218, in run
    self.loop()
    │    └ <function MissionExecutor.loop at 0x00000291AC8639D8>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 16508)>

> File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\mission\mission_template.py", line 408, in loop
    self.exec_mission()
    │    └ <function FightOnlyGeneral.exec_mission at 0x00000291AC86D5E8>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 16508)>

  File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\commission\general\OnlyFight.py", line 13, in exec_mission
    self.circle_search(self.commission_position, stop_rule=STOP_RULE_COMBAT)
    │    │             │    │                              └ 'COMBAT'
    │    │             │    └ [3720.6425600000007, -3768.7961600000003]
    │    │             └ <FightOnlyGeneral(source.mission.mission_template, started daemon 16508)>
    │    └ <function MissionExecutor.circle_search at 0x00000291AC85FDC8>
    └ <FightOnlyGeneral(source.mission.mission_template, started daemon 16508)>

  File "F:\Users\live\Desktop\PGPL-2.3\repositories\GIA_Launcher_Download_Lib\source\mission\mission_template.py", line 305, in circle_search
    if stop_func():
       └ <function MissionExecutor.<lambda> at 0x00000291AC85FD38>

TypeError: <lambda>() missing 1 required positional argument: 'x'
2024-08-23 19:45:25.869 | TRACE    | source.interaction.interaction_core:wrapper:41 -  operation: key_up | args: ('w',) | {} | function name: loop & run

**Comment by infstellar** [comment]
感谢反馈，想起来了忘记同步gitee仓库了，现在再试试
