### ISSUE TITLE
too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by roadlala** [infstellar/genshin_impact_assistant#24]
2023-02-12 19:35:13.737 | INFO     | static_lib:while_until_no_excessive_error:33 - 等待cvautotrack获取坐标
2023-02-12 19:35:13.740 | INFO     | collector_flow:run:291 - switch Flow to: BEFORE_MOVETO_COLLECTOR
Exception in thread CollectorFlow:
Traceback (most recent call last):
  File "E:\GenShin_tools\GIA Launcher\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\GenShin_tools\GIA Launcher\source\collector_flow.py", line 301, in run
    f2 = euclidean_distance_plist(self.collection_posi, self.shielded_posi_list).min() <= 30
  File "E:\GenShin_tools\GIA Launcher\source\util.py", line 199, in euclidean_distance_plist
    return np.sqrt((p1[0] - p2[:,0]) ** 2 + (p1[1] - p2[:,1]) ** 2)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by infstellar** [comment]
是最新测试版吗

**Comment by roadlala** [comment]
好像是0.5自动更新到0.6产生的问题，用0.6的lauch重新安装就好了
