### ISSUE TITLE
从源码安装教程可能需增加一段win32适配程序

### ISSUE THREAD

**Issue by YuuLong** [infstellar/genshin_impact_assistant#37]
## 源码安装使用python venv环境，出现win32gui与win32process找不到的问题

```
(venv) PS H:\genshin_impact_assistant> python genshin_assistant.py
Traceback (most recent call last):
  File "genshin_assistant.py", line 9, in <module>
    from source.webio import webio
  File "H:\genshin_impact_assistant\source\webio\__init__.py", line 1, in <module>
    from source.webio.page_manager import PageManager
    from source.util import *
  File "H:\genshin_impact_assistant\source\util.py", line 3, in <module>
    import win32gui, win32process, psutil, ctypes, pickle, traceback
ImportError: DLL load failed: 找不到指定的模块。
```
这是pywin32的一个老问题，安装后仍找不到模块
其原因为pywin32安装之后需使用脚本pywin32_postinstall.py安装
若是在项目根目录下，采用虚拟环境，则代码如下
```
python.exe venv/Scripts/pywin32_postinstall.py -install
```
若未采用虚拟环境，则需在python安装路径下使用
```
python.exe Scripts/pywin32_postinstall.py -install
```

**Comment by YuuLong** [comment]
应该是我环境配置问题，故关闭

**Comment by YuuLong** [comment]
应该是我环境配置问题，故关闭

**Comment by infstellar** [comment]
感谢，可能有助于解决GIA Launcher的一个相似问题，我之后试试

**Comment by YuuLong** [comment]
> 感谢，可能有助于解决GIA Launcher的一个相似问题，我之后试试

上述方法没有解决虚拟环境下的win32gui.dll丢失问题，但经过努力找到解决方案了，具体如下：
对于该种bug是由于找到了win32gui.pyd，但未找到win32gui.dll，该文件涵盖在pywin32_system32下的一个pywintypes37.dll的文件之中，其中37为python版本

该文件需在/sources/util.py中引入pywintypes.dll
即将该文件的前两行由
```
import time, math, shutil, sys, os, json
import win32gui, win32process, psutil, ctypes, pickle, traceback
```
改为
```
import time, math, shutil, sys, os, json, psutil, ctypes, pickle, traceback
import pywintypes
from win32 import win32gui, win32process
```
其中from win32可加可不加，看路径有没有加这个，加了就不用from

**Comment by infstellar** [comment]
好的，我还以为要在Launcher里修所以一直没修，原来改源码就行了(
