### ISSUE TITLE
每日委托到达目的地后程序出错

### ISSUE THREAD

**Issue by Dr-WeiAL** [infstellar/genshin_impact_assistant#38]
到达委托所在地后程序出错，角色没有任何操作
阵容使用的是群里发布的 钟离，班尼特，香菱，行秋
报错信息如下
```
2023-05-08 04:07:50.792 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
2023-05-08 04:07:52.555 | INFO     | source.map.detection.minimap:init_position:13 - init_position:(5825, 524)
2023-05-08 04:07:52.556 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_main
2023-05-08 04:07:54.621 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_main
2023-05-08 04:07:55.172 | INFO     | source.flow.flow_template:enter_flow:45 - Flow Switch To: INIT_TEYVAT_MOVE
2023-05-08 04:07:55.425 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
2023-05-08 04:07:57.161 | INFO     | source.map.detection.minimap:init_position:13 - init_position:(5825, 524)
2023-05-08 04:07:57.163 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_main
2023-05-08 04:07:58.992 | INFO     | source.flow.teyvat_move_flow_upgrad:init_path:169 - 不在服务区
2023-05-08 04:08:35.686 | INFO     | source.flow.teyvat_move_flow_upgrad:state_in:292 - 已到达目的地附近，本次导航结束。
2023-05-08 04:08:35.730 | INFO     | source.flow.teyvat_move_flow_upgrad:state_after:311 - landing
2023-05-08 04:08:36.808 | INFO     | source.flow.flow_template:enter_flow:45 - Flow Switch To: $END$TEYVAT_MOVE_PASS
2023-05-08 04:08:37.415 | INFO     | source.mission.mission_template:_init_sub_threading:72 - source.mission.mission_template CCT has been initialized and started.
2023-05-08 04:08:37.568 | INFO     | source.operator.switch_character_operator:continue_threading:220 - SCO is getting the character list
2023-05-08 04:08:37.693 | WARNING  | source.funclib.combat_lib:get_characters_name:379 - get characters name fail, retry 0
2023-05-08 04:08:37.958 | WARNING  | source.funclib.combat_lib:get_characters_name:379 - get characters name fail, retry 1
2023-05-08 04:08:38.367 | INFO     | source.funclib.combat_lib:get_chara_list:513 - team file set as: ['钟离', '班尼特', '香菱', '行秋']
2023-05-08 04:08:38.371 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:08:38.373 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.374 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Zhongli
2023-05-08 04:08:38.377 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.378 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Zhongli
2023-05-08 04:08:38.382 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:08:38.387 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.388 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Bennett
2023-05-08 04:08:38.391 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.392 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Bennett
2023-05-08 04:08:38.395 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:08:38.398 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.400 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Xiangling
2023-05-08 04:08:38.405 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.407 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Xiangling
2023-05-08 04:08:38.411 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:08:38.414 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.415 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Xingqiu
2023-05-08 04:08:38.419 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:08:38.420 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Xingqiu
2023-05-08 04:08:38.422 | ERROR    | source.mission.mission_template:loop:317 - ERROR in execute mission: source.mission.mission_template Character Key Empty Error
2023-05-08 04:08:38.426 | ERROR    | source.mission.mission_template:loop:318 - Character Key Empty Error
Traceback (most recent call last):

  File "E:\GIA_Launcher_v0.6.0\toolkit\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002019A7F95E8>
    └ <IncreasingDangerGeneral(source.mission.mission_template, started daemon 27112)>

  File "E:\GIA_Launcher_v0.6.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function BaseThreading.run at 0x00000201BCD994C8>
    └ <IncreasingDangerGeneral(source.mission.mission_template, started daemon 27112)>

  File "E:\GIA_Launcher_v0.6.0\source\common\base_threading.py", line 121, in run
    self.loop()
    │    └ <function MissionExecutor.loop at 0x00000201814D04C8>
    └ <IncreasingDangerGeneral(source.mission.mission_template, started daemon 27112)>

> File "E:\GIA_Launcher_v0.6.0\source\mission\mission_template.py", line 309, in loop
    self.exec_mission()
    │    └ <function IncreasingDangerGeneral.exec_mission at 0x00000201892D80D8>
    └ <IncreasingDangerGeneral(source.mission.mission_template, started daemon 27112)>

  File "E:\GIA_Launcher_v0.6.0\source\commission\general\IncreasingDanger.py", line 47, in exec_mission
    self.start_combat(mode="Shield")
    │    └ <function MissionExecutor.start_combat at 0x000002018150EB88>
    └ <IncreasingDangerGeneral(source.mission.mission_template, started daemon 27112)>

  File "E:\GIA_Launcher_v0.6.0\source\mission\mission_template.py", line 188, in start_combat
    self.CCT.continue_threading()
    │    │   └ <function CombatController.continue_threading at 0x00000201DAB9BB88>
    │    └ <CombatController(CombatController, started daemon 29432)>
    └ <IncreasingDangerGeneral(source.mission.mission_template, started daemon 27112)>

  File "E:\GIA_Launcher_v0.6.0\source\controller\combat_controller.py", line 68, in continue_threading
    self.sco.continue_threading()
    │    │   └ <function SwitchCharacterOperator.continue_threading at 0x00000201DAB9B9D8>
    │    └ <SwitchCharacterOperator(SwitchCharacterOperator, started daemon 30380)>
    └ <CombatController(CombatController, started daemon 29432)>

  File "E:\GIA_Launcher_v0.6.0\source\operator\switch_character_operator.py", line 221, in continue_threading
    self.chara_list = combat_lib.get_chara_list()
    │    │            │          └ <function get_chara_list at 0x00000201BED28DC8>
    │    │            └ <module 'source.funclib.combat_lib' from 'E:\\GIA_Launcher_v0.6.0\\source\\funclib\\combat_lib.py'>
    │    └ None
    └ <SwitchCharacterOperator(SwitchCharacterOperator, started daemon 30380)>

  File "E:\GIA_Launcher_v0.6.0\source\funclib\combat_lib.py", line 572, in get_chara_list
    raise TacticKeyEmptyError(t2t("Character Key Empty Error"))
          │                   └ <bound method GNUTranslations.gettext of <gettext.GNUTranslations object at 0x00000201BCD200C8>>
          └ <class 'source.funclib.combat_lib.TacticKeyEmptyError'>

source.funclib.combat_lib.TacticKeyEmptyError: Character Key Empty Error
2023-05-08 04:08:39.344 | INFO     | source.commission.commission_acquisition:get_commission_object:37 - get commission: ('SpreadingEvil', [3743.207642, -6851.215572])
2023-05-08 04:08:39.346 | INFO     | source.commission.commission_acquisition:get_commission_object:42 - get commission fail, try to get general commission
2023-05-08 04:08:39.783 | INFO     | source.operator.pickup_operator:run:80 - 停止自动拾取
2023-05-08 04:08:39.875 | INFO     | source.mission.mission_template:_init_sub_threading:72 - Thread-299 PUO has been initialized and started.
2023-05-08 04:08:40.139 | INFO     | source.mission.mission_template:_init_sub_threading:72 - source.mission.mission_template TMCF has been initialized and started.
2023-05-08 04:08:40.178 | INFO     | source.flow.teyvat_move_flow_upgrad:init_path:169 - 不在服务区
2023-05-08 04:08:40.362 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_main
2023-05-08 04:08:41.026 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
2023-05-08 04:08:51.268 | WARNING  | source.ui.ui:get_page:39 - 未知Page, 重新检测
2023-05-08 04:08:52.362 | WARNING  | source.ui.ui:get_page:39 - 未知Page, 重新检测
2023-05-08 04:08:53.473 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
2023-05-08 04:08:56.278 | INFO     | source.map.detection.minimap:init_position:13 - init_position:(6059, 310)
2023-05-08 04:08:56.280 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_main
2023-05-08 04:08:58.378 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_main
2023-05-08 04:08:58.915 | INFO     | source.flow.flow_template:enter_flow:45 - Flow Switch To: INIT_TEYVAT_MOVE
2023-05-08 04:08:59.170 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
2023-05-08 04:09:00.883 | INFO     | source.map.detection.minimap:init_position:13 - init_position:(6059, 310)
2023-05-08 04:09:00.884 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_main
2023-05-08 04:09:02.796 | INFO     | source.flow.teyvat_move_flow_upgrad:init_path:169 - 不在服务区
2023-05-08 04:10:11.385 | INFO     | source.flow.teyvat_move_flow_upgrad:state_in:292 - 已到达目的地附近，本次导航结束。
2023-05-08 04:10:11.434 | INFO     | source.flow.teyvat_move_flow_upgrad:state_after:311 - landing
2023-05-08 04:10:12.510 | INFO     | source.flow.flow_template:enter_flow:45 - Flow Switch To: $END$TEYVAT_MOVE_PASS
2023-05-08 04:10:18.967 | INFO     | source.mission.mission_template:_init_sub_threading:72 - source.mission.mission_template CFCF has been initialized and started.
2023-05-08 04:10:19.290 | INFO     | source.operator.switch_character_operator:continue_threading:220 - SCO is getting the character list
2023-05-08 04:10:19.532 | INFO     | source.funclib.combat_lib:get_chara_list:513 - team file set as: ['钟离', '班尼特', '香菱', '行秋']
2023-05-08 04:10:19.534 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:10:19.538 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.539 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Zhongli
2023-05-08 04:10:19.541 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.544 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Zhongli
2023-05-08 04:10:19.548 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:10:19.551 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.553 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Bennett
2023-05-08 04:10:19.554 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.557 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Bennett
2023-05-08 04:10:19.560 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:10:19.565 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.566 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Xiangling
2023-05-08 04:10:19.568 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.571 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Xiangling
2023-05-08 04:10:19.575 | WARNING  | source.funclib.combat_lib:get_chara_list:553 - 请将配对文件中的tastic_group更名为tactic_group. 已自动识别。
2023-05-08 04:10:19.578 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.580 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: Qcd_time; character name: Xingqiu
2023-05-08 04:10:19.583 | ERROR    | source.funclib.combat_lib:get_param:58 - Tactic ERROR: Key Empty
2023-05-08 04:10:19.585 | ERROR    | source.funclib.combat_lib:get_param:59 - parameter name: vision; character name: Xingqiu
```

**Comment by infstellar** [comment]
群里的文件过期了
我看了一下，你这4个角色都有默认配置，你可以把AdaptiveTeamSetup设置为true，就会自动识别了。

**Comment by infstellar** [comment]
AdaptiveTeamSetup有配队文件优先使用配队文件，你把那个老文件删掉在启动试试
