### ISSUE TITLE
在进入副本后运行报错

### ISSUE THREAD

**Issue by zhengguxiaoshi** [infstellar/genshin_impact_assistant#39]
信息如下
2023-05-15 21:48:16.431 | INFO     | source.api.pdocr_api:__init__:59 - created DBDetector and Recognizer. cost 0.79
2023-05-15 21:48:16.434 | INFO     | source.api.pdocr_api:__init__:62 - created PPOCRv3. cost 0.0
2023-05-15 21:48:16.436 | INFO     | source.api.pdocr_complete:<module>:9 - created pdocr. cost 0.8 second.
2023-05-15 21:48:17.055 | INFO     | source.map.map:<module>:395 - genshin map object created
2023-05-15 21:48:17.179 | INFO     | source.listening:listening:132 - 导入完成
2023-05-15 21:48:44.004 | INFO     | source.api.yolox_api:<module>:6 - 正在创建YOLOX对象。这可能需要一些时间。
Exception in thread TaskManager:
Traceback (most recent call last):
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\source\common\base_threading.py", line 121, in run
    self.loop()
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\source\task\task_manager.py", line 109, in loop
    self.start_stop_task(i)
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\source\task\task_manager.py", line 63, in start_stop_task
    from source.task.domain_task import DomainTask
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\source\task\domain_task.py", line 2, in <module>
    from source.flow.domain_flow_upgrad import DomainFlowController
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\source\flow\domain_flow_upgrad.py", line 10, in <module>
    from source.api import yolox_api
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\source\api\yolox_api.py", line 24, in <module>
    from yolox.data.data_augment import ValTransform
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\yolox\data\__init__.py", line 5, in <module>
    from .data_augment import TrainTransform, ValTransform
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\yolox\data\data_augment.py", line 18, in <module>
    from yolox.utils import xyxy2cxcywh
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\yolox\utils\__init__.py", line 5, in <module>
    from .allreduce_norm import *
  File "E:\genshin_b\ai\GIA_Launcher_v0.6.0\yolox\utils\allreduce_norm.py", line 9, in <module>
    from torch import distributed as dist
ImportError: cannot import name 'distributed' from 'torch' (unknown location)

**Comment by infstellar** [comment]
是从源代码运行还是Launcher运行

**Comment by zhengguxiaoshi** [comment]
Launcher运行

**Comment by infstellar** [comment]
布吉岛，可能是下载依赖的时候有缺失，使用国内配置重新安装试试

**Comment by zhengguxiaoshi** [comment]
重新下载后解决了，感谢^ω^

**Comment by infstellar** [comment]
好耶
