### ISSUE TITLE
import失败

### ISSUE THREAD

**Issue by NHCyrus** [infstellar/genshin_impact_assistant#50]
cannot import name '_pyautogui_win' from 'pyautogui' (D:\download\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pyautogui\__init__.py)

**Comment by NHCyrus** [comment]
Traceback (most recent call last):
  File "D:\download\GIA_Launcher_v0.6.0\toolkit\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\download\GIA_Launcher_v0.6.0\source\common\base_threading.py", line 121, in run
    self.loop()
  File "D:\download\GIA_Launcher_v0.6.0\source\mission\mission_manager.py", line 33, in loop
    self.exec_mission(mission_name)
  File "D:\download\GIA_Launcher_v0.6.0\source\mission\mission_manager.py", line 18, in exec_mission
    mission = get_mission_object(mission_name)
  File "D:\download\GIA_Launcher_v0.6.0\source\mission\mission_index.py", line 5, in get_mission_object
    import source.mission.missions.MissionAutoCollector
  File "D:\download\GIA_Launcher_v0.6.0\source\mission\missions\MissionAutoCollector.py", line 3, in <module>
    from source.interaction.minimap_tracker import tracker
  File "D:\download\GIA_Launcher_v0.6.0\source\interaction\minimap_tracker.py", line 2, in <module>
    from source.map.map import genshin_map
  File "D:\download\GIA_Launcher_v0.6.0\source\map\map.py", line 2, in <module>
    from source.ui.ui import ui_control
  File "D:\download\GIA_Launcher_v0.6.0\source\ui\ui.py", line 7, in <module>
    from source.interaction.interaction_core import itt
  File "D:\download\GIA_Launcher_v0.6.0\source\interaction\interaction_core.py", line 813, in <module>
    itt = InteractionBGD()
  File "D:\download\GIA_Launcher_v0.6.0\source\interaction\interaction_core.py", line 82, in __init__
    import source.interaction.interaction_normal
  File "D:\download\GIA_Launcher_v0.6.0\source\interaction\interaction_normal.py", line 4, in <module>
    import win32api, win32con, pyautogui
  File "D:\download\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pyautogui\__init__.py", line 546, in <module>
    from . import _pyautogui_win as platformModule
ImportError: cannot import name '_pyautogui_win' from 'pyautogui' (D:\download\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pyautogui\__init__.py)

**Comment by infstellar** [comment]
依赖没有安装成功，试试使用大陆下载配置，关闭代理然后卸载重装

**Comment by NHCyrus** [comment]
使用的就是大陆下载配置 我重装一遍尝试一下

**Comment by NHCyrus** [comment]
哦，config/settings/config.json文件已经被修改General.json 望md文件修改一下。

**Comment by NHCyrus** [comment]
大陆下载配置还是缺少这个依赖。

**Comment by NHCyrus** [comment]
我使用github下载尝试一下

**Comment by infstellar** [comment]
> 哦，config/settings/config.json文件已经被修改General.json 望md文件修改一下。

好的，感谢反馈

**Comment by infstellar** [comment]
应该是pyautogui的问题，你可以Google一下`ImportError: cannot import name 'pyautogui_win' from 'pyautogui'`，也可能跟你的Windows版本有关系？

**Comment by NHCyrus** [comment]
windows版本是win11 22h2 22621.1555

**Comment by NHCyrus** [comment]
google出的是嵌套引用问题

**Comment by infstellar** [comment]
不是很懂⊙(・◇・)？在安装的时候有报错吗？或者复制一下安装的日志

**Comment by NHCyrus** [comment]
2023-05-30 17:58:13.547 | INFO     | source.util:<module>:70 - language set as: zh_CN
2023-05-30 17:58:15.599 | INFO     | source.util:<module>:70 - language set as: zh_CN
2023-05-30 17:58:15.840 | INFO     | __main__:<module>:26 - 正在初始化，请稍后
2023-05-30 17:58:15.864 | WARNING  | source.common.static_lib:get_handle:22 - 找不到句柄
2023-05-30 17:58:15.882 | INFO     | source.interaction.interaction_core:__init__:72 - InteractionBGD created
2023-05-30 17:58:15.895 | WARNING  | common.static_lib:get_handle:22 - 找不到句柄
2023-05-30 17:58:16.124 | CRITICAL | __main__:<module>:41 - 导入依赖时错误
2023-05-30 17:58:16.125 | WARNING  | source.error_code.util:log:32 - IMPORT_ERROR_1_1
2023-05-30 17:58:16.128 | ERROR    | __main__:<module>:43 - cannot import name '_pyautogui_win' from 'pyautogui' (D:\download\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pyautogui\__init__.py)
Traceback (most recent call last):

> File "genshin_assistant.py", line 39, in <module>
    import source.common.generic_event
           │      └ <module 'source.common' from 'D:\\download\\GIA_Launcher_v0.6.0\\source\\common\\__init__.py'>
           └ <module 'source' from 'D:\\download\\GIA_Launcher_v0.6.0\\source\\__init__.py'>

  File "D:\download\GIA_Launcher_v0.6.0\source\common\generic_event.py", line 2, in <module>
    from source.interaction.interaction_core import itt

  File "D:\download\GIA_Launcher_v0.6.0\source\interaction\interaction_core.py", line 813, in <module>
    itt = InteractionBGD()
          └ <class 'source.interaction.interaction_core.InteractionBGD'>

  File "D:\download\GIA_Launcher_v0.6.0\source\interaction\interaction_core.py", line 82, in __init__
    import source.interaction.interaction_normal

  File "D:\download\GIA_Launcher_v0.6.0\source\interaction\interaction_normal.py", line 4, in <module>
    import win32api, win32con, pyautogui
           │         └ <module 'win32con' from 'D:\\download\\GIA_Launcher_v0.6.0\\toolkit\\lib\\site-packages\\win32\\lib\\win32con.py'>
           └ <module 'win32api' from 'D:\\download\\GIA_Launcher_v0.6.0\\toolkit\\lib\\site-packages\\win32\\win32api.pyd'>

  File "D:\download\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pyautogui\__init__.py", line 546, in <module>
    from . import _pyautogui_win as platformModule

ImportError: cannot import name '_pyautogui_win' from 'pyautogui' (D:\download\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pyautogui\__init__.py)
2023-05-30 17:58:17.000 | INFO     | source.webio.webio:main:37 - webio启动完成
2023-05-30 17:58:29.054 | INFO     | source.webio.pages:_event_thread:294 - 未找到会话，可能由于窗口关闭。请刷新页面重试。

**Comment by infstellar** [comment]
没有遇到过这种问题⊙(・◇・)？ 这几天我看看pyautogui的开发日志，看看能不能找到点东西

**Comment by infstellar** [comment]
感觉还是系统版本不兼容

**Comment by NHCyrus** [comment]
那没办法了🌚

**Comment by infstellar** [comment]
看了一下,pyautogui在5月25号有一次更新,我在下次GIA更新的时候把版本回退到`0.9.53`看看能不能解决问题.

**Comment by NHCyrus** [comment]
好的，昨天我用win10电脑测试时，发现无论是github源还是gitee源，都出现了pip 无法找到文件。 希望可以测试一下什么问题。

**Comment by gongfuture** [comment]
我刚更新了0.9.54，没有出现你这种情况，要不单独pip uninstall再install试试？

**Comment by NHCyrus** [comment]
我的电脑是win11没有这个情况。但是还是无法导入。

**Comment by gongfuture** [comment]
刚看了一下你用的是launcher，那我就不大清楚了qwq，我是直接拉的源码跑的

**Comment by NHCyrus** [comment]
我拉源码更离谱。拉都拉不下来完，拉一半不拉了，

**Comment by NHCyrus** [comment]
能请教一下怎么拉的源码嘛。我每次都是拉着拉着出现错误。

**Comment by NHCyrus** [comment]
能否将源码以压缩包的形式发给我呢，我的邮箱为NHCyrus@163.com.

**Comment by NHCyrus** [comment]
Traceback (most recent call last):
  File "D:\download\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\download\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\download\GIA_Launcher_v0.6.0\giainstaller.py", line 278, in <module>
    import installer_setup
  File "D:\download\GIA_Launcher_v0.6.0\installer_setup.py", line 1, in <module>
    from source.util import *
  File "D:\download\GIA_Launcher_v0.6.0\source\util.py", line 3, in <module>
    import win32gui, win32process, psutil, ctypes, pickle, traceback
ImportError: DLL load failed: 找不到指定的模块。
更换了一个win10设备 怎么错误变成这个了。

**Comment by infstellar** [comment]
> Traceback (most recent call last): File "D:\download\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "D:\download\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\download\GIA_Launcher_v0.6.0\giainstaller.py", line 278, in import installer_setup File "D:\download\GIA_Launcher_v0.6.0\installer_setup.py", line 1, in from source.util import * File "D:\download\GIA_Launcher_v0.6.0\source\util.py", line 3, in import win32gui, win32process, psutil, ctypes, pickle, traceback ImportError: DLL load failed: 找不到指定的模块。 更换了一个win10设备 怎么错误变成这个了。

缺少系统DLL依赖，安装C++全家桶试试
