### ISSUE TITLE
领取日常奖励出错

### ISSUE THREAD

**Issue by gongfuture** [infstellar/genshin_impact_assistant#54]
发生在启动领取奖励时

以下日志

2023-06-01 11:28:40.367 | INFO     | source.task.task_manager:start_stop_task:83 - 任务ClaimRewardTask启动。
2023-06-01 11:28:40.369 | DEBUG    | source.common.base_threading:pause_threading:29 -  pause threading
2023-06-01 11:28:40.369 | DEBUG    | source.common.base_threading:_add_sub_threading:90 - sub threading  has been add.
2023-06-01 11:28:40.370 | DEBUG    | source.common.base_threading:continue_threading:34 -  continue threading
2023-06-01 11:28:40.576 | DEBUG    | source.common.base_threading:continue_threading:34 - source.mission.mission_template continue threading
2023-06-01 11:28:40.804 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
2023-06-01 11:28:40.817 | DEBUG    | source.ui.ui:ui_goto:99 - Page switch: page_main -> page_bigmap
2023-06-01 11:28:40.817 | TRACE    | source.interaction.interaction_core:wrapper:35 -  operation: key_press | args: ('m',) | {} | function name: ui_goto & ensure_page
2023-06-01 11:28:41.866 | DEBUG    | source.ui.ui:ui_goto:88 - Page arrive: page_bigmap
2023-06-01 11:28:41.867 | DEBUG    | source.interaction.interaction_core:delay:576 - delay: 0.5 |function name: ui_goto |comment: ui goto is waiting genshin animation
2023-06-01 11:28:42.630 | TRACE    | source.api.pdocr_api:analyze:70 - det boxes: [[81,56],[206,54],[206,75],[81,77]]rec text: 每日委托奖励 rec score:0.896331 det boxes: [[82,114],[205,114],[205,134],[82,134]]rec text: 探索派遣奖励 rec score:0.903537 det boxes: [[79,168],[164,168],[164,192],[79,192]]rec text: 锻造奖励 rec score:0.998040 det boxes: [[82,229],[228,229],[228,250],[82,250]]rec text: 新的可挑战牌手 rec score:0.993626 
2023-06-01 11:28:42.630 | INFO     | source.task.claim_reward.claim_reward:get_available_reward:25 - ['Commission', 'Expedition']
2023-06-01 11:28:42.638 | TRACE    | source.interaction.interaction_core:wrapper:35 -  operation: key_up | args: ('w',) | {} | function name: pause_threading & _add_sub_threading
2023-06-01 11:28:42.638 | DEBUG    | source.common.base_threading:pause_threading:29 - TeyvatMoveFlow pause threading
2023-06-01 11:28:42.638 | DEBUG    | source.common.base_threading:_add_sub_threading:90 - sub threading TeyvatMoveFlow has been add.
2023-06-01 11:28:42.639 | INFO     | source.mission.mission_template:_init_sub_threading:78 - source.mission.mission_template TMCF has been initialized and started.
2023-06-01 11:28:42.640 | ERROR    | source.mission.mission_template:loop:368 - ERROR in execute mission: source.mission.mission_template 'ClaimRewardMission' object has no attribute 'PUO'
2023-06-01 11:28:42.641 | ERROR    | source.mission.mission_template:loop:369 - 'ClaimRewardMission' object has no attribute 'PUO'
Traceback (most recent call last):

  File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000019D525C64C8>
    └ <ClaimRewardTask(, started daemon 2220)>

  File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function BaseThreading.run at 0x0000019D74B5B1F8>
    └ <ClaimRewardTask(, started daemon 2220)>

  File "D:\Projects\genshin_impact_assistant\source\common\base_threading.py", line 121, in run
    self.loop()
    │    └ <function ClaimRewardTask.loop at 0x0000019D337C2B88>
    └ <ClaimRewardTask(, started daemon 2220)>

  File "D:\Projects\genshin_impact_assistant\source\task\claim_reward\claim_reward.py", line 83, in loop
    self.blocking_startup(self.CRM)
    │    │                │    └ <ClaimRewardMission(source.mission.mission_template, initial daemon)>
    │    │                └ <ClaimRewardTask(, started daemon 2220)>
    │    └ <function AdvanceThreading.blocking_startup at 0x0000019D74B5B318>
    └ <ClaimRewardTask(, started daemon 2220)>

  File "D:\Projects\genshin_impact_assistant\source\common\base_threading.py", line 133, in blocking_startup
    threading_obj.loop()
    │             └ <function MissionExecutor.loop at 0x0000019D333159D8>
    └ <ClaimRewardMission(source.mission.mission_template, initial daemon)>

> File "D:\Projects\genshin_impact_assistant\source\mission\mission_template.py", line 360, in loop
    self.exec_mission()
    │    └ <function ClaimRewardMission.exec_mission at 0x0000019D337C29D8>
    └ <ClaimRewardMission(source.mission.mission_template, initial daemon)>

  File "D:\Projects\genshin_impact_assistant\source\task\claim_reward\claim_reward.py", line 63, in exec_mission
    self.move_along("Katheryne20230408124320i0", is_precise_arrival=True)
    │    └ <function MissionExecutor.move_along at 0x0000019D3339BB88>
    └ <ClaimRewardMission(source.mission.mission_template, initial daemon)>

  File "D:\Projects\genshin_impact_assistant\source\mission\mission_template.py", line 208, in move_along
    r = self.move(MODE="PATH", path_dict = path_dict, is_tp = is_tp, is_reinit=is_reinit, is_precise_arrival=is_precise_arrival)
        │    │                             │                  │                │                             └ True
        │    │                             │                  │                └ True
        │    │                             │                  └ True
        │    │                             └ OrderedDict([('break_position', [[2526.316, -5796.719], [2530.9186000000004, -5792.8835], [2536.799700000001, -5782.9112], [2...
        │    └ <function MissionExecutor.move at 0x0000019D3339BA68>
        └ <ClaimRewardMission(source.mission.mission_template, initial daemon)>

  File "D:\Projects\genshin_impact_assistant\source\mission\mission_template.py", line 157, in move
    if not self.PUO.pause_threading_flag:
           └ <ClaimRewardMission(source.mission.mission_template, initial daemon)>

AttributeError: 'ClaimRewardMission' object has no attribute 'PUO'
2023-06-01 11:28:42.695 | TRACE    | source.interaction.interaction_core:wrapper:35 -  operation: key_up | args: ('w',) | {} | function name: loop & blocking_startup
2023-06-01 11:28:42.696 | DEBUG    | source.common.base_threading:pause_threading:29 - source.mission.mission_template pause threading
2023-06-01 11:28:42.696 | DEBUG    | source.common.base_threading:pause_threading:29 -  pause threading
2023-06-01 11:28:42.834 | INFO     | source.task.task_manager:loop:124 - task ClaimRewardTask end.
2023-06-01 11:28:42.835 | INFO     | source.task.task_manager:start_stop_task:92 - 任务结束
2023-06-01 11:28:42.836 | DEBUG    | source.common.base_threading:stop_threading:38 -  stopping.
2023-06-01 11:28:42.836 | DEBUG    | source.common.base_threading:_clean_sub_threading:94 -  stop source.mission.mission_template
2023-06-01 11:28:42.836 | DEBUG    | source.common.base_threading:stop_threading:38 - source.mission.mission_template stopping.
2023-06-01 11:28:42.836 | DEBUG    | source.common.base_threading:_clean_sub_threading:94 - source.mission.mission_template stop TeyvatMoveFlow
2023-06-01 11:28:42.836 | DEBUG    | source.common.base_threading:stop_threading:38 - TeyvatMoveFlow stopping.
2023-06-01 11:28:42.836 | INFO     | source.task.task_manager:loop:126 - all task end.
2023-06-01 11:28:42.909 | DEBUG    | source.common.base_threading:run:105 -  stop.

**Comment by infstellar** [comment]
下次更新修复~

**Comment by infstellar** [comment]
已更新,如果问题已修复请关闭issue~

**Comment by gongfuture** [comment]
好耶，成功~
