### ISSUE TITLE
运行GIA Launcher.exe后出现FileNotFoundError: [Errno 2] No translation file found for domain: 'zh_CN'

### ISSUE THREAD

**Issue by Chobits-Yuno** [infstellar/genshin_impact_assistant#55]
[ success ]
zh_CN
python G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0/source/msgfmt.py -o G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po
python: can't open file 'G:\program': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\giainstaller.py", line 278, in <module>
    import installer_setup
  File "G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\installer_setup.py", line 1, in <module>
    from source.util import *
  File "G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\source\util.py", line 15, in <module>
    from source.i18n import t2t, GLOBAL_LANG
  File "G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\source\i18n.py", line 35, in <module>
    l10n = gettext.translation(GLOBAL_LANG, localedir=os.path.join(ROOT_PATH, r"translation/locale"), languages=[GLOBAL_LANG])
  File "G:\program files\Genshin Impact Assistant\GIA_Launcher_v0.6.0\toolkit\lib\gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'zh_CN'
The program is over. This may be due to an error or an active end.

(,,´•ω•)ノ"(´っω•｀。)

**Comment by infstellar** [comment]
下次更新修复

**Comment by infstellar** [comment]
已更新,如果问题已修复请关闭issue~
