### ISSUE TITLE
使用后半段角色定位为normal的角色会报错

### ISSUE THREAD

**Issue by gongfuture** [infstellar/genshin_impact_assistant#57]
例如温迪
2023-06-03 11:34:12.301 | INFO     | source.operator.switch_character_operator:continue_threading:242 - SCO is getting the character list
2023-06-03 11:34:12.356 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[160,22],[206,22],[206,49],[160,49]]rec text: 温迪 rec score:0.997693 
2023-06-03 11:34:12.387 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[116,22],[200,20],[200,42],[116,44]]rec text: 雷电将军 rec score:0.951136 
2023-06-03 11:34:12.420 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[131,25],[193,25],[193,50],[131,50]]rec text: 钟离 rec score:0.793796 
2023-06-03 11:34:12.451 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[86,26],[190,26],[190,46],[86,46]]rec text: 珊瑚宫心海 rec score:0.967004 
2023-06-03 11:34:12.507 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[160,22],[206,22],[206,49],[160,49]]rec text: 温迪 rec score:0.997652 
2023-06-03 11:34:12.536 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[116,22],[200,20],[200,42],[116,44]]rec text: 雷电将军 rec score:0.952256 
2023-06-03 11:34:12.566 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[131,25],[193,25],[193,50],[131,50]]rec text: 钟离 rec score:0.787733 
2023-06-03 11:34:12.594 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[85,26],[189,26],[189,46],[85,46]]rec text: 珊瑚宫心海 rec score:0.881148 
2023-06-03 11:34:12.596 | INFO     | source.funclib.combat_lib:get_chara_list:503 - 在tactic文件夹中没有找到当前组队的tactic文件['Venti', 'Raiden Shogun', 'Zhongli', 'Sangonomiya Kokomi']
2023-06-03 11:34:12.648 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[160,22],[206,22],[206,49],[160,49]]rec text: 温迪 rec score:0.997543 
2023-06-03 11:34:12.680 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[116,22],[200,20],[200,42],[116,44]]rec text: 雷电将军 rec score:0.953108 
2023-06-03 11:34:12.714 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[131,25],[193,25],[193,50],[131,50]]rec text: 钟离 rec score:0.794981 
2023-06-03 11:34:12.745 | TRACE    | source.api.pdocr_api:analyze:71 - det boxes: [[85,25],[192,25],[192,49],[85,49]]rec text: 珊瑚宫心海 rec score:0.960032 
2023-06-03 11:34:12.748 | ERROR    | keyboard:<lambda>:649 - An error has been caught in function '<lambda>', process 'MainProcess' (26736), thread 'Thread-4' (14424):
Traceback (most recent call last):

  File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000262C96864C8>
    └ <Thread(Thread-4, started daemon 14424)>

  File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000262C9686288>
    └ <Thread(Thread-4, started daemon 14424)>

  File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-4, started daemon 14424)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-4, started daemon 14424)>
    │    └ <bound method GenericListener.process of <keyboard._KeyboardListener object at 0x00000262EBBF6608>>
    └ <Thread(Thread-4, started daemon 14424)>

  File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
       │    │                 └ KeyboardEvent([ down)
       │    └ <function _KeyboardListener.pre_process_event at 0x00000262EBBE5E58>
       └ <keyboard._KeyboardListener object at 0x00000262EBBF6608>

  File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\site-packages\keyboard\__init__.py", line 218, in pre_process_event
    callback(event)
    │        └ KeyboardEvent([ down)
    └ <function add_hotkey.<locals>.<lambda> at 0x00000262EBC85558>

> File "D:\Users\gongf\anaconda3\envs\genshin_impact_assistant\lib\site-packages\keyboard\__init__.py", line 649, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())
                     │   │             │            │ │             │          │ │            │                            │             │ │              └ <function startstop at 0x00000262EBC85168>
                     │   │             │            │ │             │          │ │            │                            │             │ └ 'down'
                     │   │             │            │ │             │          │ │            │                            │             └ KeyboardEvent([ down)
                     │   │             │            │ │             │          │ │            │                            └ 'down'
                     │   │             │            │ │             │          │ │            └ {}
                     │   │             │            │ │             │          │ └ 26
                     │   │             │            │ │             │          └ KeyboardEvent([ down)
                     │   │             │            │ │             └ 'up'
                     │   │             │            │ └ 'down'
                     │   │             │            └ KeyboardEvent([ down)
                     │   │             └ 'down'
                     │   └ 'down'
                     └ KeyboardEvent([ down)

  File "D:\Projects\genshin_impact_assistant\source\listening.py", line 116, in startstop
    switch_combat_loop()
    └ <function switch_combat_loop at 0x00000262EBC7EA68>

  File "D:\Projects\genshin_impact_assistant\source\listening.py", line 84, in switch_combat_loop
    t1.continue_threading()
    │  └ <function CombatController.continue_threading at 0x00000262A7C569D8>
    └ <CombatController(CombatController, started daemon 29164)>

  File "D:\Projects\genshin_impact_assistant\source\controller\combat_controller.py", line 68, in continue_threading
    self.sco.continue_threading()
    │    │   └ <function SwitchCharacterOperator.continue_threading at 0x00000262A7C56828>
    │    └ <SwitchCharacterOperator(SwitchCharacterOperator, started daemon 30684)>
    └ <CombatController(CombatController, started daemon 29164)>

  File "D:\Projects\genshin_impact_assistant\source\operator\switch_character_operator.py", line 243, in continue_threading
    self.chara_list = combat_lib.get_chara_list()
    │    │            │          └ <function get_chara_list at 0x0000026283303288>
    │    │            └ <module 'source.funclib.combat_lib' from 'D:\\Projects\\genshin_impact_assistant\\source\\funclib\\combat_lib.py'>
    │    └ None
    └ <SwitchCharacterOperator(SwitchCharacterOperator, started daemon 30684)>

  File "D:\Projects\genshin_impact_assistant\source\funclib\combat_lib.py", line 507, in get_chara_list
    team = generate_teamfile_automatic()
           └ <function generate_teamfile_automatic at 0x00000262833033A8>

  File "D:\Projects\genshin_impact_assistant\source\funclib\combat_lib.py", line 476, in generate_teamfile_automatic
    team_file[ordinal_numeral]["priority"] = POSITION2PRIORITY[team_file[ordinal_numeral]["position"]]+curr_name_list.index(name)
    │         │                              │                 │         │                             │              │     └ 'Venti'
    │         │                              │                 │         │                             │              └ <method 'index' of 'list' objects>
    │         │                              │                 │         │                             └ ['Venti', 'Raiden Shogun', 'Zhongli', 'Sangonomiya Kokomi']
    │         │                              │                 │         └ 'first'
    │         │                              │                 └ {'first': OrderedDict([('E_short_cd_time', 6), ('E_long_cd_time', 15), ('Elast_time', 0), ('Epress_time', 0), ('Qcd_time', 15...
    │         │                              └ {'Main': 2000, 'Shield': 1000, 'Recovery': 1500, 'Support': 3000}
    │         └ 'first'
    └ {'first': OrderedDict([('E_short_cd_time', 6), ('E_long_cd_time', 15), ('Elast_time', 0), ('Epress_time', 0), ('Qcd_time', 15...

KeyError: 'Normal'

应该是每一个normal都会出现，但是我还没试过，只知道温迪和纳西妲都会出现

**Comment by infstellar** [comment]
已修复~
