### ISSUE TITLE
Ctrl+C停不了genshin_assistant.py

### ISSUE THREAD

**Issue by Zebartin** [infstellar/genshin_impact_assistant#67]
启动时`python .\genshin_assistant.py`，但Ctrl+C停不了程序，只是log一下就继续了，再次Ctrl+C没有任何反应

```shell
2023-06-13 21:11:07.436 | WARNING  | source.interaction.capture:_capture:71 - 截图失败shape: (0, 0, 4),等待2秒
请确认原神窗口没有最小化，原神启动器关闭，原神分辨率为1080p
Traceback (most recent call last):
  File ".\genshin_assistant.py", line 49, in <module>
    source.listening.listening()
  File "G:\Software\miniconda\envs\GIA\lib\site-packages\loguru\_logger.py", line 1251, in catch_wrapper
    return function(*args, **kwargs)
  File "G:\Software\genshin_impact_assistant\source\listening.py", line 129, in listening
    time.sleep(0.2)
KeyboardInterrupt
2023-06-13 21:11:09.443 | WARNING  | source.common.static_lib:get_handle:22 - 找不到句柄
```

**Comment by infstellar** [comment]
是的，python多线程有时无法通过ctrl+c停止
