### ISSUE TITLE
安装成功 但是启动失败

### ISSUE THREAD

**Issue by ThreeSourLemon** [infstellar/genshin_impact_assistant#77]
+----------------------------------------------------------------------------+
|                    SUCCESSFULLY INSTALL. ACTIVATING GIA                    |
+----------------------------------------------------------------------------+
"C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\toolkit\python.exe" genshin_assistant.py
zh_CN
python "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0/source/msgfmt.py" -o "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.mo" "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\translation/locale\zh_CN\LC_MESSAGES\zh_CN.po"
2023-07-09 15:18:42.025 | INFO     | source.interaction.interaction_core:__init__:72 - InteractionBGD created
C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pydantic\_internal\_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'keep_untouched' has been renamed to 'ignored_types'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "genshin_assistant.py", line 9, in <module>
    from source.webio import webio
  File "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\source\webio\webio.py", line 15, in <module>
    from source.webio.webpages.video2path import VideoToPathPage
  File "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\source\webio\webpages\video2path.py", line 10, in <module>
    from source.map.map import genshin_map
  File "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\source\map\map.py", line 8, in <module>
    from source.map.data.teleporter_zh_CN import DICT_TELEPORTER
  File "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\source\map\data\teleporter_zh_CN.py", line 1, in <module>
    from source.map.extractor.reader import TeleporterModel
  File "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\source\map\extractor\reader.py", line 19, in <module>
    class PointInfoModel(BaseModel):
  File "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pydantic\_internal\_model_construction.py", line 96, in __new__
    namespace, config_wrapper.ignored_types, class_vars, base_field_names
  File "C:\Users\Administrator\Desktop\GIA_Launcher_v0.6.0\toolkit\lib\site-packages\pydantic\_internal\_model_construction.py", line 332, in inspect_namespace
    code='model-field-missing-annotation',
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `first_item = <cached_property.cached_property object at 0x000001521856EEC8>`. All model fields require a type annotation; if `first_item` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.0.2/u/model-field-missing-annotation
The program is over. This may be due to an error or an active end.

我这个应该怎么才能解决

**Comment by infstellar** [comment]
看起来跟隔壁的PR有关系，我去修一下

**Comment by infstellar** [comment]
临时修补了一下

**Comment by ThreeSourLemon** [comment]
> 临时修补了一下

试了下 确实可以了
