### ISSUE TITLE
error_code: 128

### ISSUE THREAD

**Issue by wish2333** [infstellar/genshin_impact_assistant#80]
2023-07-12 10:23:16.245 | INFO     | logger:hr:62 - ==================== 获取仓库分支 ====================
2023-07-12 10:23:16.246 | INFO     | utils:execute:171 - "D:/Game/PGPL-1.0.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
2023-07-12 10:23:19.638 | INFO     | utils:execute:178 - [ failure ], error_code: 128
2023-07-12 10:23:19.638 | INFO     | utils:show_error:145 - Update failed
2023-07-12 10:23:19.639 | INFO     | utils:show_error:147 -
2023-07-12 10:23:19.639 | INFO     | utils:show_error:148 - Last command: "D:/Game/PGPL-1.0.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
error_code: 128
2023-07-12 10:23:19.640 | INFO     | utils:show_error:150 - Please check your deploy settings in config. and re-open Launcher.exe
Traceback (most recent call last):
  File "D:\Game\PGPL-1.0.0\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Game\PGPL-1.0.0\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Game\PGPL-1.0.0\main.py", line 516, in <module>
    GitManager(launching_config).git_install()
  File "D:\Game\PGPL-1.0.0\main.py", line 115, in git_install
    keep_changes=self.KeepLocalChanges,
  File "D:\Game\PGPL-1.0.0\main.py", line 71, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
  File "D:\Game\PGPL-1.0.0\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError
The program is over. This may be due to an error or an active end.

**Comment by infstellar** [comment]
关代理了吗

**Comment by FurukawaNagisar** [comment]
> 关代理了吗

.大佬我这也是这种情况。开关代理都没变化
2023-07-12 10:37:44.683 | INFO     | utils:execute:171 - "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.1/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe: No module named pip
2023-07-12 10:37:44.767 | INFO     | utils:execute:178 - [ failure ], error_code: 1
2023-07-12 10:37:44.768 | INFO     | utils:show_error:145 - Update failed
2023-07-12 10:37:44.769 | INFO     | utils:show_error:147 -
2023-07-12 10:37:44.769 | INFO     | utils:show_error:148 - Last command: "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.1/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
error_code: 1
2023-07-12 10:37:44.771 | INFO     | utils:show_error:150 - Please check your deploy settings in config. and re-open Launcher.exe
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\main.py", line 517, in <module>
    PipManager(launching_config).pip_install()
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\main.py", line 166, in pip_install
    self.execute(f'{self.pip()} install --upgrade pip{arg}')
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError
The program is over. This may be due to an error or an active end.

**Comment by FurukawaNagisar** [comment]
> 关代理了吗
重复几次后就这样
in PGL/PGPL-1.0.1/PGPL-1.0.1/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
error_code: 1
2023-07-12 10:52:24.794 | INFO     | utils:show_error:150 - Please check your deploy settings in config. and re-open Launcher.exe
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\main.py", line 517, in <module>
    PipManager(launching_config).pip_install()
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\main.py", line 166, in pip_install
    self.execute(f'{self.pip()} install --upgrade pip{arg}')
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError
The program is over. This may be due to an error or an active end.

**Comment by wish2333** [comment]
> 关代理了吗

关闭代理了，重装之后问题依然存在

**Comment by infstellar** [comment]
> > 关代理了吗
> > 重复几次后就这样
> > 2023-07-12 10:54:16.452 | INFO     | logger:hr:62 - ==================== 更新PIP ====================
> > 2023-07-12 10:54:16.453 | INFO     | utils:execute:171 - "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.1/PGPL-1.0.1/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
> > C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe: No module named pip
> > 2023-07-12 10:54:16.538 | INFO     | utils:execute:178 - [ failure ], error_code: 1
> > 2023-07-12 10:54:16.539 | INFO     | utils:show_error:145 - Update failed
> > 2023-07-12 10:54:16.540 | INFO     | utils:show_error:147 -
> > 2023-07-12 10:54:16.540 | INFO     | utils:show_error:148 - Last command: "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.1/PGPL-1.0.1/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
> > error_code: 1
> > 2023-07-12 10:54:16.542 | INFO     | utils:show_error:150 - Please check your deploy settings in config. and re-open Launcher.exe
> > Traceback (most recent call last):
> > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\lib\runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\lib\runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\main.py", line 517, in 
> > PipManager(launching_config).pip_install()
> > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\main.py", line 166, in pip_install
> > self.execute(f'{self.pip()} install --upgrade pip{arg}')
> > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\utils.py", line 180, in execute
> > raise ExecutionError
> > utils.ExecutionError
> > The program is over. This may be due to an error or an active end.

试试1.0.2

**Comment by infstellar** [comment]
> > 关代理了吗
> 
> 关闭代理了，重装之后问题依然存在

https://github.com/GenshinImpactAssistant/GIA-Document/blob/42491098c6dd1f823c2b1c82ce6577313437ce45/zh_CN/install.md
试试老版本

**Comment by wish2333** [comment]
> 
旧版本依旧报错[ failure ], error_code: 128
==================== FETCH REPOSITORY BRANCH ====================
<<< FOR CN USER: 重要: 如果你正在使用GITHUB地址，确保你已经启动WATT TOOLKIT或其他加速器 >>>
"D:/Game/GIA_Launcher_v0.6.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
fatal: unable to access 'https://github.com/GenshinImpactAssistant/GIA_Launcher_Download_Lib/': SSL certificate problem: unable to get local issuer certificate
[ failure ], error_code: 128
--- Logging error ---
Traceback (most recent call last):
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 276, in <module>
    GitManager().git_install()
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 176, in git_install
    keep_changes=self.KeepLocalChanges,
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 134, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 96, in execute
    self.show_error(command, error_code)
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 103, in show_error
    logger2.info("Update failed", 0)
Message: 'Update failed'
Arguments: (0,)

Last command: "D:/Game/GIA_Launcher_v0.6.0/toolkit/Git/mingw64/bin/git.exe" fetch origin main
error_code: 128
Please check your deploy settings in installer_config.json and re-open GIA Launcher.exe
Traceback (most recent call last):
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Game\GIA_Launcher_v0.6.0\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 276, in <module>
    GitManager().git_install()
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 176, in git_install
    keep_changes=self.KeepLocalChanges,
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 134, in git_repository_init
    self.execute(f'"{self.git}" fetch {source} {branch}')
  File "D:\Game\GIA_Launcher_v0.6.0\giainstaller.py", line 97, in execute
    raise ExecutionError
__main__.ExecutionError
The program is over. This may be due to an error or an active end.

**Comment by FurukawaNagisar** [comment]
> > > 关代理了吗
> > > 重复几次后就这样
> > > 2023-07-12 10:54:16.452 | INFO     | logger:hr:62 - ==================== 更新PIP ====================
> > > 2023-07-12 10:54:16.453 | INFO     | utils:execute:171 - "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.1/PGPL-1.0.1/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
> > > C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe: No module named pip
> > > 2023-07-12 10:54:16.538 | INFO     | utils:execute:178 - [ failure ], error_code: 1
> > > 2023-07-12 10:54:16.539 | INFO     | utils:show_error:145 - Update failed
> > > 2023-07-12 10:54:16.540 | INFO     | utils:show_error:147 -
> > > 2023-07-12 10:54:16.540 | INFO     | utils:show_error:148 - Last command: "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.1/PGPL-1.0.1/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
> > > error_code: 1
> > > 2023-07-12 10:54:16.542 | INFO     | utils:show_error:150 - Please check your deploy settings in config. and re-open Launcher.exe
> > > Traceback (most recent call last):
> > > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\lib\runpy.py", line 193, in _run_module_as_main
> > > "**main**", mod_spec)
> > > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\toolkit\lib\runpy.py", line 85, in _run_code
> > > exec(code, run_globals)
> > > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\main.py", line 517, in
> > > PipManager(launching_config).pip_install()
> > > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\main.py", line 166, in pip_install
> > > self.execute(f'{self.pip()} install --upgrade pip{arg}')
> > > File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.1\PGPL-1.0.1\utils.py", line 180, in execute
> > > raise ExecutionError
> > > utils.ExecutionError
> > > The program is over. This may be due to an error or an active end.
> 
> 试试1.0.2

2023-07-12 13:25:35.475 | INFO     | logger:hr:66 - <<< 下载PYTHON成功，解压压缩包 >>>
2023-07-12 13:25:35.580 | INFO     | logger:hr:66 - <<< INSTALLING PIP >>>
2023-07-12 13:25:35.582 | INFO     | utils:execute:171 - "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.2/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.2/toolkit/get-pip.py
C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.2/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe: can't open file 'C:/Users/Administrator/Desktop/Software/Genshin': [Errno 2] No such file or directory
2023-07-12 13:25:35.661 | INFO     | utils:execute:178 - [ failure ], error_code: 2
2023-07-12 13:25:35.662 | INFO     | utils:show_error:145 - Update failed
2023-07-12 13:25:35.662 | INFO     | utils:show_error:147 -
2023-07-12 13:25:35.663 | INFO     | utils:show_error:148 - Last command: "C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.2/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" C:/Users/Administrator/Desktop/Software/Genshin PGL/PGPL-1.0.2/toolkit/get-pip.py
error_code: 2
2023-07-12 13:25:35.666 | INFO     | utils:show_error:150 - Please check your NETWORK ENVIROUMENT and re-open Launcher.exe
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\main.py", line 331, in run
    self.execute(f'"{self.python_path}" -m pip install -r {os.path.join(ROOT_PATH, "toolkit", "basic_requirements.txt")}')
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\main.py", line 520, in <module>
    PythonManager(launching_config).run()
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\main.py", line 336, in run
    self.download_python_zip()
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\main.py", line 251, in download_python_zip
    self.execute(f'"{self.python_path}" {os.path.join(ROOT_PATH, "toolkit", "get-pip.py")}')
  File "C:\Users\Administrator\Desktop\Software\Genshin PGL\PGPL-1.0.2\utils.py", line 180, in execute
    raise ExecutionError
utils.ExecutionError
The program is over. This may be due to an error or an active end.
请按任意键继续. . .

**Comment by wish2333** [comment]
> > > 关代理了吗
> > 
> > 
> > 关闭代理了，重装之后问题依然存在
> 
> https://github.com/GenshinImpactAssistant/GIA-Document/blob/42491098c6dd1f823c2b1c82ce6577313437ce45/zh_CN/install.md 试试老版本

0.60版本安装成功，感谢~

**Comment by GenLiya** [comment]
改哪里啊有没有大佬教一下啊
