### ISSUE TITLE
程序启动错误

### ISSUE THREAD

**Issue by FurukawaNagisar** [infstellar/genshin_impact_assistant#91]
2023-07-23 09:47:05.113 | INFO     | logger:hr:73 - +----------------------------------------------------------------------------------------------------+
2023-07-23 09:47:05.115 | INFO     | logger:hr:74 - |                    SUCCESSFULLY INSTALL. ACTIVATING PYTHON-GIT-PROGRAM-LAUNCHER                    |
2023-07-23 09:47:05.116 | INFO     | logger:hr:75 - +----------------------------------------------------------------------------------------------------+
2023-07-23 09:47:05.117 | INFO     | pages:_start:130 - execute: "C:\Users\Administrator\Desktop\Software\Genshin\PGPL-2.0.0\PGPL-2.0.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\python.exe" genshin_assistant.py

Traceback (most recent call last):
  File "genshin_assistant.py", line 6, in <module>
    import source.util
  File "C:\Users\Administrator\Desktop\Software\Genshin\PGPL-2.0.0\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\util.py", line 19, in <module>
    from source.i18n import t2t, GLOBAL_LANG
  File "C:\Users\Administrator\Desktop\Software\Genshin\PGPL-2.0.0\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib\source\i18n.py", line 39, in <module>
    po_file_path = os.path.join(ROOT_PATH, r'translation/locale', GLOBAL_LANG, 'LC_MESSAGES', f'{GLOBAL_LANG}.po')
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ntpath.py", line 115, in join
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\genericpath.py", line 153, in _check_arg_types
TypeError: join() argument must be str or bytes, not 'NoneType'

C:\Users\Administrator\Desktop\Software\Genshin\PGPL-2.0.0\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib>

**Comment by infstellar** [comment]
没看懂，发个日志文件看看

**Comment by FurukawaNagisar** [comment]
> 没看懂，发个日志文件看看
日志里没找到，但是最后显示百分之百但是卡在C:\Users\Administrator\Desktop\Software\Genshin\PGPL-2.0.0\PGPL-2.0.0\repositories\GIA_Launcher_Download_Lib>不动了
![111](https://github.com/infstellar/genshin_impact_assistant/assets/61621101/c217158f-4650-4db5-a82d-6020b1687cdb)
